kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-app-4
  labels:
    type: redis-nfs-claim
    app: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs